name: Validate

on: 
  push:
    branches:
      - develop

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install Angular
        run: |
          npm i @angular/cli@14.1.2
          npm install @angular-devkit/build-angular
          ng add @ng-bootstrap/ng-bootstrap

      - name: Install dependencies
        run: npm install

      # - name: Tests
      #   run: npm run test

      - name: Build
        run: ng build --configuration development