name: Validate

on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install Angular
        run: |
          npm install -g @angular/cli
          npm install @angular-devkit/build-angular

      - name: Cache node_modules
        uses: actions/cache@v2.0.0
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cache-name }}-
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      # - name: Tests
      #   run: npm run test

      - name: Build
        run: ng build --configuration development